package main

const (
	INTERNAL_JSON_KEYS_PREFIX = "__"
	INDIVIDUAL_ID_KEY         = INTERNAL_JSON_KEYS_PREFIX + "id"

	MAX_SQLX_PLACEHOLDERS = 250

	DEFAULT_PAGESIZE = 30
	MAX_PAGESIZE     = 500

	API_NO_RATELIMIT = 1 << 0
	API_FEED         = 1 << 1
	API_ADMIN        = 1 << 2

	TOKEN_FEED  = 1 << 0
	TOKEN_ADMIN = 1 << 1
)
